name: Build and publish Registry Package

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: conductor-oss/conductor
          ref: ${{ github.ref_name }}

      - name: Add private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build Server and publish to registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          BUILD_NAME: conductor-oss-server
          BUILD_VERSION: ${{ github.ref_name }}
          BUILD_COMMIT: ${{ github.sha }}
        with:
          name: ${{github.repository_owner}}/conductor-oss-server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          dockerfile: docker/server/Dockerfile
          tags: ${{ steps.get_version.outputs.VERSION }}
          buildargs: BUILD_NAME,BUILD_VERSION,BUILD_COMMIT

      - name: Build UI and publish to registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          BUILD_NAME: conductor-oss-ui
          BUILD_VERSION: ${{ github.ref_name }}
          BUILD_COMMIT: ${{ github.sha }}
        with:
          name: ${{github.repository_owner}}/conductor-oss-ui
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          dockerfile: docker/ui/Dockerfile
          tags: ${{ steps.get_version.outputs.VERSION }}
          buildargs: BUILD_NAME,BUILD_VERSION,BUILD_COMMIT
